
#ifndef LOG_MODULES_H
#define LOG_MODULES_H

/* Modules (would be auto-generated by a script pre-compile time) */
#define LOG_MODULE_main     (0x00000000)
#define LOG_MODULE_module1  (0x00000001)
#define LOG_MODULE_module2  (0x00000002)
#define LOG_MODULE_module3  (0x00000003)

#endif
